### PR TITLE
Edit menu to match home page and Drupal pages

### PR DESCRIPTION
**Pull request by mizejewski**

### CODE REVIEW

**Comment by Trott** [comment]
Looks good to me. HIt the "Merge pull request" button whenever you want it to go live.

**Comment by mizejewski** [comment]
Will do. It also looks like the Zendesk widget code is missing. I might add it to _site/index.html and push it just so you can have a look sometime before it is merged.

**Comment by Trott** [comment]
`_site/index.html` is auto-generated code. You'll need to add it to just plain ol' `index.html`. `_site/index.html` is generated from that and the contents of `_layouts`.

**Comment by mizejewski** [comment]
Thanks -- just saw gitignore and figured that out. I meant to push to my own repo, but I just pushed it to upstream. Seems OK though http://search.library.ucsf.edu/#measles

**Comment by Trott** [comment]
Yes, looks good to me. While you're in there, you might as well remove the hotjar code.

**Pull request merged**
