### PR TITLE
Make it so layout is the same for tablet and larger going to single colu...

### PR DESCRIPTION
**Pull request by mizejewski**
...mn only for small screens  (Medium-x applies to every screen tablet or larger size unless you specify large-x.)

### CODE REVIEW

**Comment by Trott** [comment]
I went ahead and merged this, but note that one issue with the new layout is that the catalog results can be so long that it masks the fact that there are three other results boxes below.
screen shot 2015-02-17 at 4 57 59 pm

Compared to the way it was before, where you are encouraged to scroll down:

screen shot 2015-02-17 at 4 59 25 pm

**Comment by Trott** [comment]
Oh, that's fixable with CSS. Will do that in a bit...

**Comment by mizejewski** [comment]
To match the height of the boxes, that's done in tweaks.css

/\* Keep results boxes all the same height when they are 3-across */
@media only screen and (min-width: 64.063em) {
.results-list {
    height: 15em;
    overflow-y: auto;
}

That min-width looks like it may have been done according to some formula, so I didn’t just pull a number out of the air to change it.

**Comment by Trott** [comment]
That's better.

screen shot 2015-02-17 at 5 03 58 pm

**Comment by mizejewski** [comment]
Yes! We can sit with that for a day or so, and if it seems too narrow, I’ll edit so that it has 3 across for large and 2 across for medium.

**Comment by mizejewski** [comment]
Here's a portrait view of an iPad
img_0001

**Pull request merged**
